// Only run against the disposable local database; never use a shared tenant.
const assert = require('node:assert/strict')
const { randomUUID } = require('crypto')
if (!/^postgresql:\/\/auna_test@127\.0\.0\.1:55439\//.test(process.env.DATABASE_URL || '')) {
  throw new Error('Esta prueba requiere la base temporal local del puerto 55439')
}
const { prisma, prismaTransaction } = require('../src/models/prisma')
const orders = require('../src/modules/orders/controller')
const { restoreStockMap } = require('../src/services/bomStock')
const { applyPayment } = require('../src/modules/receivables')
const call = (fn, req) => new Promise((resolve, reject) => {
  let status = 200
  const res = { status(code) { status = code; return res }, json(body) {
    if (status >= 400) reject(Object.assign(new Error(body.message), { status }))
    else resolve(body)
  } }
  Promise.resolve(fn(req, res, reject)).catch(reject)
})

async function main() {
  const suffix = randomUUID().slice(0, 8)
  const company = await prisma.company.create({ data: { name: 'Prueba pedidos', code: suffix } })
  const branch = await prisma.branch.create({ data: { company_id: company.id, name: 'Principal', code: suffix } })
  const role = await prisma.role.upsert({ where: { name: 'Admin' }, create: { name: 'Admin' }, update: {} })
  const user = await prisma.user.create({ data: { name: 'Prueba', email: `${suffix}@example.test`, password: 'unused', role_id: role.id } })
  const category = await prisma.productCategory.create({ data: { company_id: company.id, name: 'Prueba' } })
  const customer = await prisma.supplier.create({ data: { company_id: company.id, name: 'Cliente', contact: 'Prueba', party_type: 'CUSTOMER', credit_limit: 1000 } })
  const stockStatus = await prisma.stockStatus.upsert({ where: { name: 'Disponible' }, create: { name: 'Disponible' }, update: {} })
  const cash = await prisma.paymentMethod.upsert({ where: { name: 'Efectivo' }, create: { name: 'Efectivo', is_credit: false }, update: {} })
  const credit = await prisma.paymentMethod.upsert({ where: { name: 'Crédito' }, create: { name: 'Crédito', is_credit: true }, update: {} })
  await prisma.saleStatus.upsert({ where: { name: 'Completada' }, create: { name: 'Completada' }, update: {} })
  const product = await prisma.product.create({ data: { company_id: company.id, category_id: category.id, supplier_id: customer.id, name: 'Producto', status_id: stockStatus.id, price: 10, cost: 3, stock: 0, min_stock: 0 } })
  await prisma.$transaction(tx => restoreStockMap(tx, new Map([[product.id, 30]]), branch.id, { reason: 'PURCHASE' }))
  const req = (id, body = {}, extra = {}) => ({ params: { id }, body, companyId: company.id, branchId: branch.id, user: { sub: user.id, role: { name: 'Admin' } }, ...extra })
  const order = await call(orders.create, req('', { customer_contact_id: customer.id, customer: 'Cliente', items: [{ product_id: product.id, qty: 10 }], valid_until: '2099-01-01' }))
  assert.equal(order.fulfillment_mode, 'SEPARATE')
  await call(orders.confirm, req(order.id))
  const line = order.lines[0]
  const firstKey = randomUUID()
  const deliver = (qty, key = randomUUID()) => call(orders.deliver, req(order.id, { request_key: key, lines: [{ line_id: line.id, qty }] }))
  const first = await deliver(4, firstKey)
  assert.equal(first.order.lines[0].qty_fulfilled, 4)
  await deliver(4, firstKey)
  assert.equal(await prisma.orderDelivery.count({ where: { document_id: order.id } }), 1)
  assert.equal(await prisma.sale.count({ where: { branch_id: branch.id } }), 0)
  assert.equal((await prisma.productStock.findUnique({ where: { product_id_branch_id: { product_id: product.id, branch_id: branch.id } } })).stock, 26)
  // A correction restores inventory and reservation; repeating it is harmless.
  const reverseReq = req(order.id, {}, { params: { id: order.id, deliveryId: first.delivery.id } })
  await call(orders.reverseDelivery, reverseReq)
  await call(orders.reverseDelivery, reverseReq)
  assert.equal((await prisma.productStock.findUnique({ where: { product_id_branch_id: { product_id: product.id, branch_id: branch.id } } })).stock, 30)
  await deliver(4)
  await prisma.product.update({ where: { id: product.id }, data: { cost: 9 } })
  const deliveries = await Promise.allSettled([deliver(6), deliver(6)])
  assert.equal(deliveries.filter(result => result.status === 'fulfilled').length, 1)
  const invoiceReq = req(order.id, { request_key: randomUUID(), payment_method_id: credit.id, due_date: '2099-01-01', lines: [{ line_id: line.id, qty: 10 }] })
  const billed = await call(orders.invoice, invoiceReq)
  assert.equal(billed.sale.payment_status, 'PENDING')
  assert.equal(Number(billed.sale.total), 100)
  const saleItem = await prisma.saleItem.findFirst({ where: { sale_id: billed.sale.id } })
  assert.equal(Number(saleItem.unit_cost), 6.6)
  assert.equal((await prisma.productStock.findUnique({ where: { product_id_branch_id: { product_id: product.id, branch_id: branch.id } } })).stock, 20)
  assert.equal((await call(orders.invoice, invoiceReq)).sale.id, billed.sale.id)
  await assert.rejects(call(orders.invoice, req(order.id, { ...invoiceReq.body, request_key: randomUUID() })), /pendiente/)
  await assert.rejects(call(orders.cancel, req(order.id)))
  await prisma.$transaction(tx => applyPayment(tx, { customerId: customer.id, branchId: branch.id, amount: 40, paidAt: new Date(), paymentMethodId: cash.id, userId: user.id }))
  const paid = await prisma.sale.findUnique({ where: { id: billed.sale.id }, include: { paymentEntries: true } })
  assert.equal(paid.payment_status, 'PARTIAL')
  assert.equal(Number(paid.paymentEntries[0].amount), 40)
  const other = await prisma.company.create({ data: { name: 'Otro tenant', code: `X${suffix}` } })
  await assert.rejects(call(orders.invoice, { ...invoiceReq, companyId: other.id }), /no encontrado/)
  console.log('OK: entregas parciales, reversión, concurrencia, venta consolidada, costo histórico, crédito, abono, tenant e idempotencia')
}
main().catch(error => { console.error(error); process.exitCode = 1 }).finally(async () => {
  await prisma.$disconnect()
  if (prismaTransaction !== prisma) await prismaTransaction.$disconnect()
})
